version: "3"

services:
    app:
        build: .
        ports:
            - "8080:8080"
        networks:
            - s-network

    postgres:
        image: postgres:latest
        ports:
            - "5433:5432"
        environment:
            POSTGRES_USER: uthpala
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: postgres
        networks:
          - s-network
        volumes:
            - postgres_s_data:/var/lib/postgresql/data

networks:
    s-network:
        driver: bridge

volumes:
    postgres_s_data: